app/views/api.py
from flask import Blueprint, render_template, request, redirect, jsonify, url_for, g, send_file, current_app, flash
from flask import current_app as app
from flask_login import login_required, current_user
from rq import push_connection, pop_connection, Queue
import redis

from datetime import datetime
from pathlib import Path
import pandas as pd
import os

from app import tasks
from app.influx import sendQueryInflux, removeUselessColumns
from app.forms import *

api_bp = Blueprint('api', __name__, url_prefix='/api')

#
# Open API
#

@api_bp.route('/query_date_range', methods=['POST'])
@login_required
def query_date_range():

    form = QueryAPI_DateRange_Field(request.form)
    if form.validate_on_submit():
        start = form.start_date.data.strftime("%Y-%m-%dT%H:%M:%SZ")
        stop = form.stop_date.data.strftime("%Y-%m-%dT%H:%M:%SZ")
        field = form.fields.data
        device = form.sensors.data

        # Check if start date its wrong
        if(start > stop):
            flash('Error. La fecha de inicio no puede ser mayor a la fecha de fin.')
            return redirect(url_for('dashboard.open_api'))

        query = ''' 
        from(bucket:"{}")
            |> range(start: {}, stop: {})
            |> filter(fn:(r) =>
            r._measurement == "sensorWizether" and
            r._field == "{}" and
            r.device == "{}")
        '''.format(app.config['INFLUX_BUCKET'], start, stop, field, device)

        #print(query)

        root_path = Path(current_app.root_path).parent
        upload_path = os.path.join(root_path, 'api_tmp')

        df_result = sendQueryInflux(query)

        filename = 'data_' + datetime.now().strftime("%Y-%m-%d") + '.csv'
        filename_path = os.path.join(upload_path, filename)
        
        if df_result.empty:
            flash('Error. No se han encontrado datos')
            return redirect(url_for('dashboard.open_api'))
        else:
            df_result = removeUselessColumns(df_result)
            df_result.to_csv(filename_path, index = False)

        return send_file(filename_path, as_attachment=True) 
    else:
        flash('Error. Revisa los datos introducidos y vuelve a probar.')
        return redirect(url_for('dashboard.open_api'))


@api_bp.route('/query_all_date_range', methods=['POST'])
@login_required
def query_date_range_all():

    form = QueryAPI_DateRange_All(request.form)
    if form.validate_on_submit():
        start = form.start_date.data.strftime("%Y-%m-%dT%H:%M:%SZ")
        stop = form.stop_date.data.strftime("%Y-%m-%dT%H:%M:%SZ")
        device = form.sensors.data

        # Check if start date its wrong
        if(start > stop):
            flash('Error. La fecha de inicio no puede ser mayor a la fecha de fin.')
            return redirect(url_for('dashboard.open_api'))

        query = ''' 
        from(bucket:"{}")
            |> range(start: {}, stop: {})
            |> filter(fn:(r) =>
            r._measurement == "sensorWizether" and
            r.device == "{}")
        '''.format(app.config['INFLUX_BUCKET'], start, stop, device)

        #print(query)

        root_path = Path(current_app.root_path).parent
        upload_path = os.path.join(root_path, 'api_tmp')

        df_result = sendQueryInflux(query)

        filename = 'data_' + datetime.now().strftime("%Y-%m-%d") + '.csv'
        filename_path = os.path.join(upload_path, filename)

        if df_result.empty:
            flash('Error. No se han encontrado datos')
            return redirect(url_for('dashboard.open_api'))
        else:
            # Remove useless cols
            df_result = removeUselessColumns(df_result)
            df_result.to_csv(filename_path, index = False)

        return send_file(filename_path, as_attachment=True) 
    else:
        flash('Error. Revisa los datos introducidos y vuelve a probar.')
        return redirect(url_for('dashboard.open_api'))

@api_bp.route('/query_history_device', methods=['POST'])
@login_required
def query_history_device():

    form = QueryAPI_history_device(request.form)
    if form.validate_on_submit():
        device = form.sensors.data

        query = ''' 
            from(bucket:"{}")
                |> range(start: 2021-03-01T00:00:00Z, stop: now())
                |> filter(fn:(r) =>
                r._measurement == "sensorWizether" and
                r.device == "{}")
        '''.format(app.config['INFLUX_BUCKET'], device)

        #print(query)

        root_path = Path(current_app.root_path).parent
        upload_path = os.path.join(root_path, 'api_tmp')

        df_result = sendQueryInflux(query)

        filename = 'data_' + datetime.now().strftime("%Y-%m-%d") + '.csv'
        filename_path = os.path.join(upload_path, filename)

        if df_result.empty:
            flash('Error. No se han encontrado datos')
            return redirect(url_for('dashboard.open_api'))
        else:
            df_result = removeUselessColumns(df_result)
            df_result.to_csv(filename_path, index = False)

        return send_file(filename_path, as_attachment=True) 
    else:
        flash('Error. Revisa los datos introducidos y vuelve a probar.')
        return redirect(url_for('dashboard.open_api'))


@api_bp.route('/query_lastweek_device', methods=['POST'])
@login_required
def query_lastweek_device():

    form = QueryAPI_lastweek_device(request.form)
    if form.validate_on_submit():
        device = form.sensors.data

        query = ''' 
            from(bucket:"{}")
                |> range(start: -7d, stop: now())
                |> filter(fn:(r) =>
                r._measurement == "sensorWizether" and
                r.device == "{}")
        '''.format(app.config['INFLUX_BUCKET'], device)

        #print(query)

        root_path = Path(current_app.root_path).parent
        upload_path = os.path.join(root_path, 'api_tmp')

        df_result = sendQueryInflux(query)

        filename = 'data_' + datetime.now().strftime("%Y-%m-%d") + '.csv'
        filename_path = os.path.join(upload_path, filename)

        if df_result.empty:
            flash('Error. No se han encontrado datos')
            return redirect(url_for('dashboard.open_api'))
        else:
            df_result = removeUselessColumns(df_result)
            df_result.to_csv(filename_path, index = False)

        return send_file(filename_path, as_attachment=True) 
    else:
        flash('Error. Revisa los datos introducidos y vuelve a probar.')
        return redirect(url_for('dashboard.open_api'))


@api_bp.route('/query_lastweek_device_max', methods=['POST'])
@login_required
def query_lastweek_device_max():

    form = QueryAPI_lastweek_device_max(request.form)
    if form.validate_on_submit():
        device = form.sensors.data

        query = ''' 
            from(bucket:"{}")
                |> range(start: -7d, stop: now())
                |> filter(fn:(r) =>
                r._measurement == "sensorWizether" and
                r.device == "{}")
                |> max()
        '''.format(app.config['INFLUX_BUCKET'], device)

        #print(query)

        root_path = Path(current_app.root_path).parent
        upload_path = os.path.join(root_path, 'api_tmp')

        df_result = sendQueryInflux(query)

        filename = 'data_' + datetime.now().strftime("%Y-%m-%d") + '.csv'
        filename_path = os.path.join(upload_path, filename)

        if df_result.empty:
            flash('Error. No se han encontrado datos')
            return redirect(url_for('dashboard.open_api'))
        else:
            df_result = removeUselessColumns(df_result)
            df_result.to_csv(filename_path, index = False)

        return send_file(filename_path, as_attachment=True) 
    else:
        flash('Error. Revisa los datos introducidos y vuelve a probar.')
        return redirect(url_for('dashboard.open_api'))

#
# Tasks
#

# Task view
@api_bp.route('/tasks/', methods=['GET'])
@login_required
def gettasks():
    queue = Queue()
    error = []
    try:
        jobs = queue.jobs
    except Exception as ex:
        error.append(str(ex))
        # print(ex)
        return render_template('dashboard/tasks.html',
                               error_list=error,
                               user=current_user)

    return render_template('dashboard/tasks.html',
                           jobs=jobs,
                           error_list=error,
                           user=current_user)


# Enqueue Task
@api_bp.route('/enqueue_task/<task_name>', methods=['GET', 'POST'])
@login_required
def enqueue_task(task_name):
    app.logger.info("Enqueuing task " + task_name)

    queue = Queue(default_timeout=3600)

    # Running a function (inside tasks.py) by its name
    # This is either pure genius or a massive hack
    task = queue.enqueue(getattr(tasks, task_name), result_ttl=1000)

    app.logger.info("Task enqueued. Currently " + str(len(queue)) + " tasks in queue.")

    return jsonify({}), 202, {
        'Location':
        url_for('api.job_status',
                _external=True,
                _scheme='https',
                job_id=task.get_id())
    }


# Query Job Status. Finding the result of a Job
@api_bp.route('/status/<job_id>')
@login_required
def job_status(job_id):
    queue = Queue()
    job = queue.fetch_job(job_id)
    if job is None:
        response = {'status': 'unknow'}
    else:
        print(job.to_dict())
        response = {
            'status': job.get_status(),
            'result': str(job.result)
        }

        if job.is_failed:
            response['message'] = job.exc_info.strip().split('\n')[-1]

        app.logger.info(response)

    return jsonify(response)


#
# Getting the redis connection or setup
#
def get_redis_connection():
    redis_connection = getattr(g, '_redis_connection', None)
    if redis_connection is None:
        redis_url = app.config['REDIS_URL']
        redis_connection = g._redis_connection = redis.from_url(redis_url)

    return redis_connection


#
# RQ Management for Redis Queues

app/views/dashboard.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask import current_app as app
from flask_login import login_required, logout_user, current_user

from app import tasks, DEVICES
from app.permission import restricted_role
from app.forms import *

dashboard_bp = Blueprint('dashboard', __name__)

#
# Home page
#
@dashboard_bp.route('/dashboard')
@login_required
def home():

    src_temp = "https://grafana.wize.ranii.pro/d-solo/SUaxNOwMk/portal-graphs-20212230?orgId=1&refresh=5m&panelId=2"
    src_hum = "https://grafana.wize.ranii.pro/d-solo/SUaxNOwMk/portal-graphs-20212230?orgId=1&refresh=5m&panelId=4"
    src_air = "https://grafana.wize.ranii.pro/d-solo/SUaxNOwMk/portal-graphs-20212230?orgId=1&refresh=5m&panelId=6"
    src_press = "https://grafana.wize.ranii.pro/d-solo/SUaxNOwMk/portal-graphs-20212230?orgId=1&refresh=5m&panelId=9"
    src_loud = "https://grafana.wize.ranii.pro/d-solo/SUaxNOwMk/portal-graphs-20212230?orgId=1&refresh=5m&panelId=10"
    src_uptime = "https://grafana.wize.ranii.pro/d-solo/grAXaj8Mz/test-dashboard?orgId=1&refresh=5m&panelId=6"

    return render_template('dashboard/home.html', user=current_user, src_temp=src_temp,
                                                                     src_hum=src_hum,
                                                                     src_air=src_air,
                                                                     src_press=src_press,
                                                                     src_loud=src_loud,
                                                                     src_uptime=src_uptime)

#
# Mis estaciones
#
@dashboard_bp.route('/my_stations')
@login_required
def my_stations():
    return render_template('dashboard/my_stations.html', user=current_user, devices=DEVICES)


#
# Nueva Estación
#
@dashboard_bp.route('/new_station', methods=['GET', 'POST'])
@login_required
def new_station():

    form = NewStation()
    if form.validate_on_submit():
        device = form.device_name.data
        lat = form.lat.data
        lon = form.lon.data
        place = form.place.data

        new_station = {'device': device,
                'latitude': lat,
                'longitude': lon,
                'location': place,
                'version': 'v1'}

        # On production --> De-sync of WSGI
        #DEVICES.append(new_station)

        flash('Estación registrada con éxito en latitud: {}, longitud:{} y {}'.format(lat, lon, place))
        return redirect(url_for('dashboard.new_station'))

    return render_template('dashboard/new_station.html', user=current_user, form=form)

#
# Solicitar Nueva estación
#
@dashboard_bp.route('/ask_station', methods=['GET', 'POST'])
@login_required
def ask_station():
    form = AskStation()
    if form.validate_on_submit():
        email = form.email.data

        flash('Hemos registrado tu solicitud. Nos pondremos en contacto con {}. ¡Muchas gracias!'.format(email))
        return redirect(url_for('dashboard.ask_station'))

    return render_template('dashboard/ask_station.html', user=current_user, form=form)

#
# Nuevo Gateway
#
@dashboard_bp.route('/new_gateway', methods=['GET', 'POST'])
@login_required
def new_gateway():
    form = NewGateway()
    if form.validate_on_submit():
        lat = form.lat.data
        lon = form.lon.data
        place = form.place.data
        power = form.power.data

        flash('Gateway registrado con éxito en latitud: {}, longitud:{}, {} y con potencia {}'.format(lat, lon, place, power))
        return redirect(url_for('dashboard.new_gateway'))

    return render_template('dashboard/new_gateway.html', user=current_user, form=form)


#
# Open API
#
@dashboard_bp.route('/openapi')
@login_required
def open_api():

    form1 = QueryAPI_DateRange_Field()
    form2 = QueryAPI_DateRange_All()
    form3 = QueryAPI_history_device()

    form4 = QueryAPI_lastweek_device()
    form5 = QueryAPI_lastweek_device_max()

    return render_template('dashboard/api.html', user=current_user, form1=form1,
                                                                    form2=form2,
                                                                    form3=form3,
                                                                    form4=form4,
                                                                    form5=form5)

app/templates/dashboard/api.html
{% extends "dashboard/base.html" %}
{% block title %}Open API{% endblock %}

{% set active_page = "api" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Obtener datos entre un rango de fechas</h5>
                    <form action="/api/query_date_range" method="POST">            
                        <fieldset class="start_date">
                            {{ form1.start_date.label }}
                            {{ form1.start_date(class='datepicker') }}
                        </fieldset>
                
                        <fieldset class="stop_date">
                            {{ form1.stop_date.label }}
                            {{ form1.stop_date(class='datepicker') }}
                        </fieldset>
                
                        <fieldset class="selector">
                            {{ form1.fields.label }}
                            {{ form1.fields}}
                        </fieldset>
                        
                        <fieldset class="sensors">
                            {{ form1.sensors.label }}
                            {{ form1.sensors }}
                        </fieldset>

                        {{ form1.hidden_tag() }}
                
                        <div class="submit-button">
                            {{ form1.submit(class='btn btn-lg btn-primary btn-block', style='margin-top: 5%') }}
                        </div>
                    </form>
                </div>
            </div>

        </div>

        <div class="col-md-4">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Obtener todos los datos entre un rango de fechas</h5>
                    <form action="/api/query_all_date_range" method="POST">            
                        <fieldset class="start_date">
                            {{ form2.start_date.label }}
                            {{ form2.start_date(class='datepicker') }}
                        </fieldset>
                
                        <fieldset class="stop_date">
                            {{ form2.stop_date.label }}
                            {{ form2.stop_date(class='datepicker') }}
                        </fieldset>
                        
                        <fieldset class="sensors">
                            {{ form2.sensors.label }}
                            {{ form2.sensors }}
                        </fieldset>

                        {{ form2.hidden_tag() }}
                
                        <div class="submit-button">
                            {{ form2.submit(class='btn btn-lg btn-primary btn-block', style='margin-top: 5%') }}
                        </div>
                    </form>
                </div>
            </div>

        </div>

        <div class="col-md-4">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Obtener todo el histórico de una estación</h5>
                    <form action="/api/query_history_device" method="POST">
            
                        <fieldset class="sensors">
                            {{ form3.sensors.label }}
                            {{ form3.sensors }}
                        </fieldset>
            
                        {{ form3.hidden_tag() }}
            
                        <div class="submit-button">
                            {{ form3.submit(class='btn btn-lg btn-primary btn-block', style='margin-top: 5%') }}
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div><!-- End row -->

    <div class="row" style="margin-top: 5%;">

        <div class="col-md-4">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Obtener todas las medidas de los 7 últimos dias</h5>
                    <form action="/api/query_lastweek_device" method="POST">
            
                        <fieldset class="sensors">
                            {{ form4.sensors.label }}
                            {{ form4.sensors }}
                        </fieldset>
            
                        {{ form4.hidden_tag() }}
            
                        <div class="submit-button">
                            {{ form4.submit(class='btn btn-lg btn-primary btn-block', style='margin-top: 5%') }}
                        </div>
                    </form>
                </div>
            </div>

        </div>

        <div class="col-md-4">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Obtener los valores máximos de los 7 últimos dias</h5>
                    <form action="/api/query_lastweek_device_max" method="POST">
            
                        <fieldset class="sensors">
                            {{ form5.sensors.label }}
                            {{ form5.sensors }}
                        </fieldset>
            
                        {{ form5.hidden_tag() }}
            
                        <div class="submit-button">
                            {{ form5.submit(class='btn btn-lg btn-primary btn-block', style='margin-top: 5%') }}
                        </div>
                    </form>
                </div>
            </div>


        </div>

        <div class="col-md-4">

            

        </div>

    </div>
</div><!-- End container -->

{% endblock %}

app/templates/dashboard/ask_station.html
{% extends "dashboard/base.html" %}
{% block title %}Solicitar Estación{% endblock %}

{% set active_page = "ask_station" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5 ">

            <div class="card">
                <div class="card-body">


                        <h5 class="card-title text-center">Solicitar una estación</h5>
                        <p>Facilitanos un email de contacto para que podamos transmitirte toda la
                            información necesaria sobre la estación <i>WizeTher</i>. Sin compromiso alguno,
                            te contestaremos a ese mismo email.</p>

                        <form action="/ask_station" style="text-align: center;" method="POST">            
                            <fieldset class="email" style="margin-top: 2%;">
                                {{ form.email.label }}
                                {{ form.email }}
                            </fieldset>
    
                            {{ form.hidden_tag() }}
                    
                            <div class="submit-button">
                                {{ form.submit(class='btn btn-lg btn-primary btn-block', style='margin-top: 3.5%') }}
                            </div>
                        </form>
    

                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/dashboard/base.html
{% extends "base.html" %}

{% block additional_libraries %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/dashboard.css') }}" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
{% endblock %}

{% block body %}
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="{{ url_for('dashboard.home' )}}">
            <img src="{{ url_for('static', filename='landing/img/logo_wizether_v1.png') }}" style="object-fit: cover; height: 40px; margin-left: 15%;"
            class="logo logo-display" alt="">
        </a>

        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse"
            data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="#">
                    <span data-feather="user"></span> Hola {{user.name}}!</a>
            </li>
        </ul>
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">
                    Desconectar <span data-feather="log-out"></span> </a>
            </li>
        </ul>
    </nav>
    
    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
    
                        <li class="nav-item">
                            <a class="nav-link {% if active_page == 'dashboard' %}active{% endif %}"
                                href="{{ url_for('dashboard.home') }}" style="margin-top: 2.5%;">
                                <span data-feather="home"></span>
                                Portal <span class="sr-only">(current)</span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/">
                                <span data-feather="corner-down-left"></span>
                                Inicio
                            </a>
                        </li>
                    </ul>
    
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Estaciones</span>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link {% if active_page == "my_stations" %}active{% endif %}"  href="/my_stations">
                                <span data-feather="compass"></span>
                                Mis estaciones
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link {% if active_page == "new_station" %}active{% endif %}" href="/new_station">
                                <span data-feather="cloud"></span>
                                Nueva estación
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link {% if active_page == "ask_station" %}active{% endif %}"
                                href="/ask_station">
                                <span data-feather="send"></span>
                                Solicitar estación
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link {% if active_page == "new_gateway" %}active{% endif %}"
                                href="/new_gateway">
                                <span data-feather="cpu"></span>
                                Nuevo gateway
                            </a>
                        </li>
                    </ul>
    
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Datos</span>
                    </h6>
                    <ul class="nav flex-column mb-2">
    
                        <li class="nav-item">
                            <a class="nav-link {% if active_page == "api" %}active{% endif %}" 
                                href="/openapi">
                                <span data-feather="hard-drive"></span>
                                Open API
                            </a>
                        </li>
    
                    </ul>
    
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Usuario</span>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="/change_password">
                                <span data-feather="lock"></span>
                                Cambiar contraseña
                            </a>
                        </li>
                    </ul>
    
                    {% if user.role == "admin" %}
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Admin</span>
                    </h6>
                    <ul class="nav flex-column mb-2">
    
                        <li class="nav-item">
                            <a class="nav-link" href="/signup">
                                <span data-feather="user-plus"></span>
                                Registrar usuario
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/admin">
                                <span data-feather="award"></span>
                                Administración
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="https://grafana.wize.ranii.pro/">
                                <span data-feather="pie-chart"></span>
                                Grafana
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="https://influxdb.wize.ranii.pro/">
                                <span data-feather="database"></span>
                                InfluxDB
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="https://nodered.wize.ranii.pro">
                                <span data-feather="git-merge"></span>
                                Node Red
                            </a>
                        </li>
                    </ul>
                    {% endif %}
    
                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4" style="padding-top: 20px">
                
                <!-- Flash menssages -->
                <div id="alert-message">
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-warning">
                        {{ messages[0] }}
                    </div>
                    {% endif %}
                    {% endwith %}
                </div>
                
                {% block content %}{% endblock %}
            </main>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script>
        feather.replace()
    </script>

    <script type=text/javascript>
      $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>

    {% block app_scripts %}{% endblock %}
        
    {% endblock %}